---
project: deblur_gan
experiment_desc: fpn

train:
#  files_a: &FILES_A /datasets/my_dataset/**/*.jpg
  #可以使用绝对路径
  files_a: &FILES_A ./dataset/train/blur/**/*.png
  files_b: &FILES_B ./dataset/train/sharp/**/*.png
#  files_a: &FILES_A ./dataset1/blur/*.png
#  files_b: &FILES_B ./dataset1/sharp/*.png
  size: &SIZE 256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, .9]
  scope: geometric
  corrupt: &CORRUPT
    - name: CoarseDropout
      prob: 0.5
      max_holes: 3
      max_height: 25  # 修改前为 max_h_size
      max_width: 25   # 修改前为 max_w_size
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: *FILES_A
  files_b: *FILES_B
#  files_a: &FILES_A
#  files_b: &FILES_B
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [.9, 1]
  corrupt: *CORRUPT

phase: train
warmup_num: 3
model:
  g_name: fpn_mobilenet # 生成器模型名称，或者说网络名称
  blocks: 9 # 块数，这里准确来说是残差块的块数。残差块由一个卷积层、一个实例归一化层和一个ReLU激活函数组成
  d_name: double_gan # 判别器模型名称 may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3 # 判别器层数
  content_loss: perceptual # 内容损失函数名称，这里使用的是感知损失函数
  adv_lambda: 0.001 # 对抗损失函数的权重
  disc_loss: ragan-ls # 判别器损失函数名称，这里使用的是RAGAN-LS损失函数
  learn_residual: True # 是否学习残差
  norm_layer: instance # 归一化层名称，这里使用的是实例归一化层
  dropout: True # 是否使用dropout

num_epochs: 300
train_batches_per_epoch: 1000
val_batches_per_epoch: 100
batch_size: 1
image_size: [256, 256]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: linear
  start_epoch: 150
  min_lr: 0.0000001
